### ISSUE TITLE
paperclip error

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#158]
A NameError occurred in clinics#update:

  uninitialized constant Paperclip::Storage::S3::AWS
  vendor/bundle/ruby/2.1.0/gems/paperclip-2.8.0/lib/paperclip/storage/s3.rb:241:in `rescue in exists?'

- reproduce by trying to add a new referral form and update

**Comment by bgracie** [comment]
seems like this is a known issue

http://stackoverflow.com/questions/28374401/nameerror-uninitialized-constant-paperclipstorages3aws

we upgraded aws-sdk 13 days ago..

**Comment by bgracie** [comment]
after updating, still getting this

Missing Credentials.

Unable to find AWS credentials.  You can configure your AWS credentials
a few different ways:

but looks like that's because I don't have AWS_ACCESS_KEY_ID in my ENV.  TODO ask Kelsey for it.

**Comment by bgracie** [comment]
Fix is working locally, though on staging I'm getting these errors having to do with sessions:

 ActiveRecord::StatementInvalid (PG::SyntaxError: ERROR:  zero-length delimited identifier at or near """"
: LINE 6: ..." = '2015-06-15 20:16:52.563150' WHERE "sessions"."" = 58305...

 ActiveRecord::StatementInvalid (PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint
 : INSERT INTO "sessions" ("created_at", "data", "id", "session_id", "updated_at") VALUES ($1, $2, $3, $4, $5)):

looks like AR doesn't know about the 'id' key on sessions for some reason...

**Comment by bgracie** [comment]
could have to do with a recent upgrade of authlogic

https://github.com/pathwaysmedical/frasernw/commit/e4898ebf7d489be883c5d457d3a34e4b05aa49bd#diff-e79a60dc6b85309ae70a6ea8261eaf95R55

**Comment by bgracie** [comment]
cannot replicate the issue locally

**Comment by bgracie** [comment]
this is the potential solution, though it doesn't explain why this problem cropped up now

http://stackoverflow.com/questions/16542199/rails-article-find-1-raises-activerecordstatementinvalid-on-legacy-database

**Comment by bgracie** [comment]
https://github.com/pathwaysmedical/frasernw/commit/c508b4b85ce2bd8ab7363863f97f7fd5deafd7fc

didn't fix it, and neither did reverting to master branch...  so the problem was introduced sometime before this commit

**Comment by KelseyDH** [comment]
This might be an issue with SSL. I would recommend using the aws-sdk gem config recommended by the authors.

**Comment by bgracie** [comment]
What does aws-sdk have to do with ssl?

**Comment by bgracie** [comment]
And I thought 'test' has been on ssl for awhile?

**Comment by bgracie** [comment]
Relevant bit of the backtracke -- has to do with active record sessions:

2015-06-15T21:25:10.774065+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:259:in `block in save'
2015-06-15T21:25:10.774067+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:270:in `rollback_active_record_state!'
2015-06-15T21:25:10.774068+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/transactions.rb:258:in `save'
2015-06-15T21:25:10.774069+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/session_store.rb:323:in `block in set_session'
2015-06-15T21:25:10.774071+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.21/lib/active_support/benchmarkable.rb:50:in `silence'
2015-06-15T21:25:10.774072+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.21/lib/active_record/session_store.rb:320:in `set_session'
2015-06-15T21:25:10.774073+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:327:in `commit_session'
2015-06-15T21:25:10.774075+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:211:in `context'
2015-06-15T21:25:10.774076+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in `call'
2015-06-15T21:25:10.774078+00:00 app[web.1]:   vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/middleware_tracing
