### ISSUE TITLE
Investigate Failing Background Jobs

### ISSUE THREAD

**Issue by bgracie** [pathwaysmedical/frasernw#259]
There are 45 of them

**Comment by KelseyDH** [comment]
Where are you getting this error data from?

**Comment by bgracie** [comment]
If you go `Delayed::Job.all` you get all outstanding

**Comment by KelseyDH** [comment]
I see, this appears to be the error:

```
undefined method `division' for #<NewsItem:0x007f5e2c5bf7c0>\n/app/vendor/bundle/ruby/2.1.0/gems/activemodel-3.2.22/lib/active_model/attribute_methods.rb:407:in `method_missing'\n/app/vendor/bundle/ruby/2.1.0/gems/activerecord-3.2.22/lib/active_record/attribute_methods.rb:149:in `method_missing'\n/app/app/views/public_activity/news_item/_create.html.haml:2:in `_app_views_public_activity_news_item__create_html_haml___4073149088795545767_70021480741280'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/template.rb:145:in `block in render'\n/app/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:125:in `instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/template.rb:143:in `render'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/partial_renderer.rb:238:in `block in render'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `block in instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:165:in `block in instrument_with_newrelic'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:69:in `block in trace_execution_scoped'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:67:in `trace_execution_scoped'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:164:in `instrument_with_newrelic'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/partial_renderer.rb:237:in `render'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/renderer.rb:41:in `render_partial'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/renderer.rb:15:in `render'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/helpers/rendering_helper.rb:24:in `render'\n/app/vendor/bundle/ruby/2.1.0/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'\n/app/vendor/bundle/ruby/2.1.0/gems/haml-4.0.6/lib/haml/helpers.rb:89:in `non_haml'\n/app/vendor/bundle/ruby/2.1.0/gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'\n/app/vendor/bundle/ruby/2.1.0/gems/public_activity-1.4.2/lib/public_activity/renderable.rb:109:in `render'\n/app/vendor/bundle/ruby/2.1.0/gems/public_activity-1.4.2/lib/public_activity/utility/view_helpers.rb:8:in `render_activity'\n/app/app/views/subscription_mailer/news_update_email.html.haml:16:in `block in _app_views_subscription_mailer_news_update_email_html_haml__2686615473096108683_70021480999000'\n/app/app/views/subscription_mailer/news_update_email.html.haml:11:in `each'\n/app/app/views/subscription_mailer/news_update_email.html.haml:11:in `_app_views_subscription_mailer_news_update_email_html_haml__2686615473096108683_70021480999000'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/template.rb:145:in `block in render'\n/app/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:125:in `instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/template.rb:143:in `render'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `block in instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/activesupport-3.2.22/lib/active_support/notifications.rb:123:in `instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:45:in `render_template'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/template_renderer.rb:18:in `render'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:150:in `block in render_with_newrelic'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:69:in `block in trace_execution_scoped'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer_helpers.rb:82:in `trace_execution_scoped'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/method_tracer.rb:67:in `trace_execution_scoped'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/rails3/action_controller.rb:149:in `render_with_newrelic'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/renderer.rb:36:in `render_template'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/action_view/renderer/renderer.rb:17:in `render'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:110:in `_render_template'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:103:in `render_to_body'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:88:in `render'\n/app/vendor/bundle/ruby/2.1.0/gems/actionmailer-3.2.22/lib/action_mailer/base.rb:713:in `block in collect_responses_and_parts_order'\n/app/vendor/bundle/ruby/2.1.0/gems/actionmailer-3.2.22/lib/action_mailer/base.rb:724:in `each'\n/app/vendor/bundle/ruby/2.1.0/gems/actionmailer-3.2.22/lib/action_mailer/base.rb:724:in `each_template'\n/app/vendor/bundle/ruby/2.1.0/gems/actionmailer-3.2.22/lib/action_mailer/base.rb:709:in `collect_responses_and_parts_order'\n/app/vendor/bundle/ruby/2.1.0/gems/actionmailer-3.2.22/lib/action_mailer/base.rb:648:in `mail'\n/app/app/mailers/subscription_mailer.rb:20:in `news_update_email'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/base.rb:167:in `process_action'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/base.rb:121:in `process'\n/app/vendor/bundle/ruby/2.1.0/gems/actionpack-3.2.22/lib/abstract_controller/rendering.rb:45:in `process'\n/app/vendor/bundle/ruby/2.1.0/gems/actionmailer-3.2.22/lib/action_mailer/base.rb:459:in `process'\n/app/vendor/bundle/ruby/2.1.0/gems/actionmailer-3.2.22/lib/action_mailer/base.rb:453:in `initialize'\n/app/vendor/bundle/ruby/2.1.0/gems/actionmailer-3.2.22/lib/action_mailer/base.rb:439:in `new'\n/app/vendor/bundle/ruby/2.1.0/gems/actionmailer-3.2.22/lib/action_mailer/base.rb:439:in `method_missing'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/performable_mailer.rb:6:in `perform'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:94:in `block in invoke_job'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/backend/base.rb:91:in `invoke_job'\n(eval):3:in `block in invoke_job_with_newrelic_transaction_trace'\n/app/vendor/bundle/ruby/2.1.0/gems/newrelic_rpm-3.12.0.288/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:352:in `perform_action_with_newrelic_trace'\n(eval):2:in `invoke_job_with_newrelic_transaction_trace'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block (2 levels) in run'\n/app/vendor/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'\n/app/vendor/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:101:in `call'\n/app/vendor/ruby-2.1.6/lib/ruby/2.1.0/timeout.rb:101:in `timeout'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:204:in `block in run'\n/app/vendor/ruby-2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:203:in `run'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `block in reserve_and_run_one_job'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:280:in `reserve_and_run_one_job'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:187:in `block in work_off'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `times'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:186:in `work_off'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:150:in `block (4 levels) in start'\n/app/vendor/ruby-2.1.6/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:149:in `block (3 levels) in start'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:148:in `block (2 levels) in start'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `loop'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:147:in `block in start'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:61:in `block in initialize'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:79:in `block in add'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:66:in `execute'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/lifecycle.rb:40:in `run_callbacks'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/worker.rb:146:in `start'\n/app/vendor/bundle/ruby/2.1.0/gems/delayed_job-4.0.6/lib/delayed/tasks.rb:9:in `block (2 levels) in <top (required)>'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'\n/app/vendor/bundle/ruby/2.1.0/gems/bugsnag-2.8.7/lib/bugsnag/rake.rb:12:in `execute_with_bugsnag'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'\n/app/vendor/ruby-2.1.6/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'\n/app/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'\n/app/bin/rake:37:in `<main>'

```

**Comment by KelseyDH** [comment]
I've found the problem, partially has to do with News Item not having a `division` but rather an `owner_division`
