### ISSUE TITLE
Rendering error in specialties index

### ISSUE THREAD

**Issue by dhMuse** [pathwaysmedical/frasernw#384]
E.g. `Started GET "/specialties/56" for 127.0.0.1 at 2016-04-04 11:10:19 -0700`
returns

```
Started GET "/img/filtering-divider.png" for 127.0.0.1 at 2016-04-04 11:11:00 -0700

ActionController::RoutingError (No route matches [GET] "/img/filtering-divider.png"):
  actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-timeout (0.3.2) lib/rack/timeout/core.rb:125:in `block in call'
  rack-timeout (0.3.2) lib/rack/timeout/support/timeout.rb:19:in `call'
  rack-timeout (0.3.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
  rack-timeout (0.3.2) lib/rack/timeout/core.rb:124:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.0.13) lib/rails/engine.rb:511:in `call'
  railties (4.0.13) lib/rails/application.rb:97:in `call'
  railties (4.0.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `catch'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run_machine'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.5.5) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.5) lib/rack/server.rb:264:in `start'
  railties (4.0.13) lib/rails/commands/server.rb:84:in `start'
  railties (4.0.13) lib/rails/commands.rb:76:in `block in <top (required)>'
  railties (4.0.13) lib/rails/commands.rb:71:in `tap'
  railties (4.0.13) lib/rails/commands.rb:71:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'


  Rendered /Users/danielmusekamp/.rvm/gems/ruby-2.2.4/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/_trace.erb (3.6ms)
  Rendered /Users/danielmusekamp/.rvm/gems/ruby-2.2.4/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/routes/_route.html.erb (98.2ms)
  Rendered /Users/danielmusekamp/.rvm/gems/ruby-2.2.4/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/routes/_table.html.erb (115.3ms)
  Rendered /Users/danielmusekamp/.rvm/gems/ruby-2.2.4/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (617.5ms)


Started GET "/img/filtering-divider.png" for 127.0.0.1 at 2016-04-04 11:11:05 -0700

ActionController::RoutingError (No route matches [GET] "/img/filtering-divider.png"):
  actionpack (4.0.13) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/runtime.rb:17:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack-timeout (0.3.2) lib/rack/timeout/core.rb:125:in `block in call'
  rack-timeout (0.3.2) lib/rack/timeout/support/timeout.rb:19:in `call'
  rack-timeout (0.3.2) lib/rack/timeout/support/timeout.rb:19:in `timeout'
  rack-timeout (0.3.2) lib/rack/timeout/core.rb:124:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  activesupport (4.0.13) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/lock.rb:17:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  railties (4.0.13) lib/rails/engine.rb:511:in `call'
  railties (4.0.13) lib/rails/application.rb:97:in `call'
  railties (4.0.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  newrelic_rpm (3.15.1.316) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
  rack (1.5.5) lib/rack/content_length.rb:14:in `call'
  thin (1.6.4) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.4) lib/thin/connection.rb:84:in `catch'
  thin (1.6.4) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.4) lib/thin/connection.rb:53:in `process'
  thin (1.6.4) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run_machine'
  eventmachine (1.2.0.1) lib/eventmachine.rb:194:in `run'
  thin (1.6.4) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.4) lib/thin/server.rb:162:in `start'
  rack (1.5.5) lib/rack/handler/thin.rb:16:in `run'
  rack (1.5.5) lib/rack/server.rb:264:in `start'
  railties (4.0.13) lib/rails/commands/server.rb:84:in `start'
  railties (4.0.13) lib/rails/commands.rb:76:in `block in <top (required)>'
  railties (4.0.13) lib/rails/commands.rb:71:in `tap'
  railties (4.0.13) lib/rails/commands.rb:71:in `<top (required)>'
  bin/rails:4:in `require'
  bin/rails:4:in `<main>'


  Rendered /Users/danielmusekamp/.rvm/gems/ruby-2.2.4/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/_trace.erb (2.7ms)
  Rendered /Users/danielmusekamp/.rvm/gems/ruby-2.2.4/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/routes/_route.html.erb (139.0ms)
  Rendered /Users/danielmusekamp/.rvm/gems/ruby-2.2.4/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/routes/_table.html.erb (2.4ms)
  Rendered /Users/danielmusekamp/.rvm/gems/ruby-2.2.4/gems/actionpack-4.0.13/lib/action_dispatch/middleware/templates/rescues/routing_error.erb within rescues/layout (685.4ms)
```

**Comment by dhMuse** [comment]
Cannot reproduce.
